### ISSUE TITLE
Add a license document

### ISSUE THREAD

**Issue by lmoureaux** [HSF/cmaketools#5]
According to http://lcginfo.cern.ch/pkg/cmaketools/, the code is released under the `GPL` license (which version?). There is however not a primary source, and there is no way to tell the license from this repository. The absence of a license means that any usage of this project beyond what the very restrictive Github license allows is illegal.

Please clarify the license under which the code in this repository is released.

**Comment by peremato** [comment]
Done, GPL-v3. Added LICENSE file.

**Comment by lmoureaux** [comment]
Thanks a lot! For the sake of clarity, is it GPLv3 only or GPLv3 or any later version (approved by the FSF?)?
